package com.fersaiyan.cyanbridge.devices.tunebuds

import com.fersaiyan.cyanbridge.shared.glasses.GlassesDashboardAction

internal fun GlassesDashboardAction.isSupportedForTuneBudsDashboard(): Boolean = when (this) {
    is GlassesDashboardAction.Navigate,
    GlassesDashboardAction.Scan,
    GlassesDashboardAction.Reconnect,
    GlassesDashboardAction.Disconnect,
    is GlassesDashboardAction.SelectMeetingTimer,
    GlassesDashboardAction.StartMeetingCapture,
    GlassesDashboardAction.StopMeetingCapture,
    is GlassesDashboardAction.RunNativePluginShortcut,
    is GlassesDashboardAction.SelectAssistantMode,
    GlassesDashboardAction.TestVoiceQuestion,
    GlassesDashboardAction.TestImageQuestion,
    GlassesDashboardAction.CaptureAndPreviewGlassesImage,
    GlassesDashboardAction.PreviewLastGlassesImage,
    GlassesDashboardAction.OpenExternalImageAutomationDiagnostics,
    GlassesDashboardAction.CapturePhoto,
    GlassesDashboardAction.ToggleVideo,
    GlassesDashboardAction.StartAudioRecording,
    GlassesDashboardAction.RequestMediaCount,
    GlassesDashboardAction.StartSync,
    GlassesDashboardAction.StopSync,
    GlassesDashboardAction.ToggleAdvanced,
    GlassesDashboardAction.StartAgent,
    GlassesDashboardAction.StopAgent,
    GlassesDashboardAction.RunAgentDemo,
    GlassesDashboardAction.RequestBattery,
    GlassesDashboardAction.RequestVersion,
    GlassesDashboardAction.SyncTime,
    is GlassesDashboardAction.SelectImageThumbnailQuality -> true

    is GlassesDashboardAction.SetAiWakeWordRoute,
    GlassesDashboardAction.RefreshRecordingSettings,
    is GlassesDashboardAction.SetWearingDetection,
    is GlassesDashboardAction.SetVideoRecordingDuration,
    is GlassesDashboardAction.SetAudioRecordingDuration,
    GlassesDashboardAction.RequestVolume,
    GlassesDashboardAction.AddDeviceListener,
    GlassesDashboardAction.StartClassicBluetoothScan,
    GlassesDashboardAction.DumpOtaInfo,
    GlassesDashboardAction.TestPullOta,
    is GlassesDashboardAction.RequestOtaFirmware,
    is GlassesDashboardAction.SubmitFirmwarePatchRequest,
    GlassesDashboardAction.DismissFirmwarePatchRequest,
    GlassesDashboardAction.CancelOta,
    GlassesDashboardAction.StartLivePreview,
    GlassesDashboardAction.StopLivePreview,
    GlassesDashboardAction.RequestStartWifiAdbDebug,
    GlassesDashboardAction.StopWifiAdbDebug,
    GlassesDashboardAction.MetaRegister,
    GlassesDashboardAction.MetaOpenPairing,
    GlassesDashboardAction.MetaOpenMetaAi,
    GlassesDashboardAction.MetaUnregister,
    GlassesDashboardAction.MetaStartSession,
    GlassesDashboardAction.MetaStopSession,
    GlassesDashboardAction.MetaStartStream,
    GlassesDashboardAction.MetaStopStream,
    GlassesDashboardAction.MetaCapturePhoto,
    GlassesDashboardAction.MetaViewPhoto,
    GlassesDashboardAction.MetaStartDisplay,
    GlassesDashboardAction.MetaStopDisplay,
    GlassesDashboardAction.MetaSendDiagnostics,
    GlassesDashboardAction.MeizuConnect,
    GlassesDashboardAction.MeizuDisconnect,
    GlassesDashboardAction.MeizuSendTestNotification,
    GlassesDashboardAction.MeizuShowTestTeleprompter,
    GlassesDashboardAction.MeizuSyncClock,
    GlassesDashboardAction.MeizuSetComfortBrightness -> false
}
